title: "The Apocalyptic Simulation"
author: "The Facilitator"
description: "Can A Group of Friends Survive Different Apocalyptic Situations? Find Out As We Follow Them To Hell And Back."

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 10                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: true          # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

# Theme settings
style: default               # choose between "default", "contrast" and "minimal"
dark_theme: true            # enables dark mode

navigation:                  # (optional) site navigation in the header
  - index.html
  - archive.md
  - about.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:theapocalypticsimulation@gmail.com"
  github: "https://github.com"
  podcast: "https://anchor.fm/s/95b34a8/podcast/rss"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
